/**
 * Domain-specific error codes.
 *
 * Each code is a unique machine-readable string returned in error responses
 * so that Flutter can branch on error type without parsing human text.
 */
export enum ErrorCode {
  // Auth
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_EXISTS = 'AUTH_USER_EXISTS',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID = 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_INVALID = 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_REVOKED = 'AUTH_REFRESH_TOKEN_REVOKED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  /** Credentials were valid, but the account has been suspended. */
  AUTH_USER_SUSPENDED = 'AUTH_USER_SUSPENDED',
  /** Credentials were valid, but the account is inactive. */
  AUTH_USER_INACTIVE = 'AUTH_USER_INACTIVE',
  /** Credentials were valid, but the account has not been activated yet. */
  AUTH_USER_PENDING = 'AUTH_USER_PENDING',

  // Wallet
  WALLET_INSUFFICIENT_BALANCE = 'WALLET_INSUFFICIENT_BALANCE',
  WALLET_NOT_FOUND = 'WALLET_NOT_FOUND',
  WALLET_FROZEN = 'WALLET_FROZEN',

  // Trip
  TRIP_NOT_FOUND = 'TRIP_NOT_FOUND',
  TRIP_ALREADY_PAID = 'TRIP_ALREADY_PAID',
  TRIP_NOT_OWNED = 'TRIP_NOT_OWNED',

  // Payment
  PAYMENT_ALREADY_PROCESSED = 'PAYMENT_ALREADY_PROCESSED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND',

  // Fare / Tariff
  TARIFF_NOT_FOUND = 'TARIFF_NOT_FOUND',
  TARIFF_RULE_NOT_FOUND = 'TARIFF_RULE_NOT_FOUND',
  FARE_CALCULATION_FAILED = 'FARE_CALCULATION_FAILED',
  /** The client-quoted fare disagreed with the server-calculated official fare. */
  FARE_MISMATCH = 'FARE_MISMATCH',

  // Route
  ROUTE_NOT_FOUND = 'ROUTE_NOT_FOUND',

  // Driver
  DRIVER_NOT_ACTIVE = 'DRIVER_NOT_ACTIVE',
  DRIVER_NOT_FOUND = 'DRIVER_NOT_FOUND',

  // Passenger
  PASSENGER_NOT_FOUND = 'PASSENGER_NOT_FOUND',

  // Withdrawal
  WITHDRAWAL_INSUFFICIENT_BALANCE = 'WITHDRAWAL_INSUFFICIENT_BALANCE',
  WITHDRAWAL_NOT_FOUND = 'WITHDRAWAL_NOT_FOUND',

  // Vehicle
  VEHICLE_NOT_FOUND = 'VEHICLE_NOT_FOUND',

  // General
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
}
